# Generated by Django 4.2.6 on 2023-10-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('price', models.FloatField(verbose_name='Price per item')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('cat', models.IntegerField(choices=[(1, 'Mobile'), (2, 'Shoes'), (3, 'Cloths')], verbose_name='Category')),
                ('is_available', models.BooleanField(verbose_name='Is_available')),
                ('pdetails', models.CharField(max_length=100, verbose_name='Product Details')),
                ('pimage', models.ImageField(upload_to='appimage/product', verbose_name='Upload Product Image')),
            ],
        ),
    ]
